# Generated by Django 4.1 on 2022-09-02 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(default='category/img/logo.png', upload_to='category/img')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ціна не може бути негативною!')])),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Кількість може бути негативним значенням!')])),
                ('img', models.ImageField(upload_to='catalog/img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categorymodel')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['id'],
            },
        ),
    ]
