# Generated by Django 4.1 on 2022-08-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
