# Generated by Django 4.0.6 on 2022-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='img',
            field=models.ImageField(default='category/img/logo.png', upload_to='category/img'),
        ),
    ]
