# Generated by Django 4.0.6 on 2022-08-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(upload_to='catalog/img'),
        ),
    ]
