# Generated by Django 4.1 on 2022-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='money',
            field=models.FloatField(default=10000),
        ),
    ]
