# Generated by Django 4.0.6 on 2022-08-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='img',
            field=models.ImageField(null=True, upload_to='user/img'),
        ),
    ]
