# Generated by Django 4.1 on 2022-09-02 17:43

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не відпрацьовано'), (2, 'Повернено')])),
            ],
            options={
                'verbose_name': 'Отмена',
                'verbose_name_plural': 'Отмены',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Товары заказа',
                'verbose_name_plural': 'Товары заказов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=order.models.date_now)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Прийнятий'), (2, 'Виконаний'), (3, 'Скасовано'), (4, 'Повернення')])),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
